services:
  db:
    container_name: workana_db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: workana_backend
    build: .
    image: node-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
